version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ipb_helpdesk_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: love
      POSTGRES_DB: ipb_helpdesk
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ipb_helpdesk_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:love@db:5432/ipb_helpdesk
      - SECRET_KEY=yaudalahyeah
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ipb_helpdesk_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
