name: Security Scan (SAST)

# Bagian 'on' ini yang memberitahu GitHub kapan harus jalan
on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Bandit
        run: pip install bandit
        
      - name: Run Bandit Scan
        # Kita scan folder backend/app. Jika folder tidak ditemukan, scan root '.'
        run: bandit -r . -ll --exit-zero